[package]
name = "kristforge"
version = "2.0.0"
description = "GPU-accelerated Krist miner"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"

[dependencies]
structopt = "0.3.2"
url = "2.1.0"
failure = "0.1.5"
serde = { version = "1.0.101", features = [ "derive" ] }
serde_json = "1.0.41"
hex = "0.4.0"
surf = "1.0.2"
tokio = "0.2.0-alpha.6"
url_serde = "0.2.0"
websocket = { version = "0.23.0", default-features = false, features = [ "async", "async-ssl" ] }
futures-preview = "0.3.0-alpha.19"
log = "0.4.8"
indicatif = "0.12.0"
parking_lot = "0.9.0"
lazy_static = "1.4.0"
ocl = "0.19.3"
ocl-extras = "0.1.1"
regex = "1.3.1"
ascii_tree = "0.1.1"
sha2 = "0.8.0"
rand = "0.7.2"
crossbeam = "0.7.2"
dirs = "2.0.2"
simplelog = "0.7.3"

[patch.crates-io]
# until released with fix for futures-preview 0.3.0-alpha.19
surf = { git = "https://github.com/rustasync/surf.git" }

[profile.release]
lto = true
