[package]
name = "kristforge"
version = "2.0.0"
description = "GPU-accelerated Krist miner"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = [ "derive" ] }
hex = "0.4.0"
thiserror = "1.0.9"

[profile.release]
lto = true
codegen-units = 1