[package]
name = "kristforge"
version = "2.0.0"
description = "GPU-accelerated Krist miner"
authors = ["Dominic Marcuse <dominic@marcuse.us>"]
edition = "2018"

[dependencies]
structopt = "0.3"
url = "2"
failure = "0.1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
hex = "0.4"
surf = "1"
tokio = "0.2.0-alpha.6"
url_serde = "0.2"
websocket = { version = "0.23", default-features = false, features = [ "async", "async-ssl" ] }
futures-preview = "0.3.0-alpha.19"
log = "0.4"
indicatif = "0.12"
parking_lot = "0.9"
lazy_static = "1"
ocl = "0.19"
ocl-extras = "0.1"
regex = "1"
ascii_tree = "0.1"
sha2 = "0.8"
rand = "0.7"
crossbeam = "0.7"
dirs = "2"
simplelog = "0.7"

[profile.release]
lto = true
