name: Rust tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust beta
        run: |
          rustup set profile minimal
          rustup install beta
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --nocapture
